import os

WINDOWN_WIDTH = 1520
WINDOWN_HEIGHT = 780
WINDOWN_POSITION_RIGHT = 0
WINDOWN_POSITION_DOWN = 0

COLOR_BACKGROUND = "#FFFFFF"
COLOR_HEADER = "#2E7CC3"
COLOR_TEXT = "#FFFFFF"
COLOR_DISABLED = "#CCCDD1"
COLOR_TEXT_DISABLED = "#000000"
COLOR_COMPONENT = "#676F9D"
COLOR_BUTTON = "#3EA3FF"

TEXT_FONT = "Inter"
