import os

WINDOWN_WIDTH = 1520
WINDOWN_HEIGHT = 780
WINDOWN_POSITION_RIGHT = 0
WINDOWN_POSITION_DOWN = 0

COLOR_BACKGROUND = "#D1D1D1"
COLOR_HEADER = "#2E7CC3"
COLOR_TEXT = "#2E7CC3"
COLOR_NOT_USER = "#9BA0A4"
COLOR_COMPONENT = "#FFFFFF"
COLOR_BUTTON = "#3EA3FF"

TEXT_FONT = "Inter"
